### ISSUE TITLE
Add Chihuahua and Juno

### ISSUE THREAD

**Issue by dylanschultzie** [scrtlabs/wrap.scrt.network#1]
I'm more than happy to do the bulk of the work here, just want to get it going. Please direct me!

At a minimum, this'll require:
- [x] relayers set up
- [x] icons
- [x] ibc assets defined
- [x] channels defined

**Comment by eclipse0** [comment]
Adding new assets will require at least 2+ relayers before we can active. Once we have the relayers we can add these as well. Until then maybe we can add them greyed out/disabled, but it would be irresponsible to support new assets without stable connections

**Comment by assafmo** [comment]
What's Chihuahua?

**Comment by assafmo** [comment]
We need for each coin:
1. Add the chain - see https://github.com/scrtlabs/wrap.scrt.network/blob/fba3fe7b34f23e321051f59828c574ea5591e48e/src/config.ts#L269-L281
2. Add the coin - see https://github.com/scrtlabs/wrap.scrt.network/blob/fba3fe7b34f23e321051f59828c574ea5591e48e/src/config.ts#L165-L185

Then I'll instantiate the secret tokens based on that^ data.

 But what's Chihuahua?

**Comment by dylanschultzie** [comment]
This is Chihuahua: https://info.osmosis.zone/token/HUAHUA

It's Cosmos' first dog-memecoin!
